products = [
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone SE 3",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 13",
    "Samsung Galaxy S24",
    "Samsung Galaxy S24+",
    "Samsung Galaxy S24 Ultra",
    "Samsung Galaxy Z Fold 6",
    "Samsung Galaxy Z Flip 6",
    "Samsung Galaxy Tab S9",
    "Samsung Galaxy Watch 7",
    "Samsung Galaxy Buds Pro 3",
    "Samsung Galaxy Book 4",
    "Samsung Galaxy A54",
    "Xiaomi 14",
    "Xiaomi 14 Pro",
    "Xiaomi Redmi Note 13",
    "Xiaomi Redmi Note 13 Pro",
    "Xiaomi Mi Pad 6",
    "Xiaomi Mi Watch 2",
    "Xiaomi Mi Band 8",
    "Xiaomi 13 Ultra",
    "Xiaomi Redmi K60",
    "Xiaomi Mi Mix Fold 3",
    "Vivo X100",
    "Vivo X100 Pro",
    "Vivo V29",
    "Vivo V29 Pro",
    "Vivo Y78",
    "Vivo Y78 Plus",
    "Vivo T2",
    "Vivo T2 Pro",
    "Vivo S17",
    "Vivo S17 Pro",
    "Oppo Find X6 Pro",
    "Oppo Reno 10 Pro",
    "Oppo A98 5G",
    "Oppo Pad Air 2",
    "Oppo Watch 4 Pro",
    "Oppo Enco X3",
    "Oppo Find N3",
    "Oppo K11",
    "Oppo A1 Pro",
    "Oppo Find X6 Lite",
    "OnePlus 12",
    "OnePlus 12 Pro",
    "OnePlus Nord 4",
    "OnePlus Nord CE 3",
    "OnePlus 11",
    "OnePlus 11R",
    "OnePlus 10T",
    "OnePlus 10 Pro",
    "OnePlus 9",
    "OnePlus 9 Pro",
    "Sony Xperia 1 VI",
    "Sony Xperia 5 VI",
    "Sony Xperia 10 VI",
    "Sony WH-1000XM5",
    "Sony WF-1000XM5",
    "Sony PlayStation 5 Slim",
    "Sony Alpha 7R V",
    "Sony Bravia XR A95K",
    "Sony Xperia Pro-I",
    "Sony Xperia L5"
]
